# Seed catalog of common lab tests with a canonical unit and conversion factors.
# conversions maps a source unit -> {"factor": f, "offset": o}:
#   canonical_value = source_value * f + o
# The canonical unit itself is always present with factor 1.
#
# Reference ranges here are canonical, sensible adult defaults used as a fallback
# when a report doesn't print its own range (or ranges disagree). They are NOT
# medical advice.

SEED_TESTS = [
    {
        "name": "Glucose (Fasting)",
        "slug": "glucose-fasting",
        "category": "Metabolic",
        "canonical_unit": "mg/dL",
        "conversions": {"mg/dL": {"factor": 1}, "mmol/L": {"factor": 18.0}},
        "ref_low": 70,
        "ref_high": 99,
        "aliases": ["glucose", "fasting glucose", "fbs", "blood sugar"],
    },
    {
        "name": "Hemoglobin A1c",
        "slug": "hba1c",
        "category": "Metabolic",
        "canonical_unit": "%",
        # IFCC mmol/mol -> NGSP %: % = 0.09148 * mmol/mol + 2.152
        "conversions": {"%": {"factor": 1}, "mmol/mol": {"factor": 0.09148, "offset": 2.152}},
        "ref_low": None,
        "ref_high": 5.6,
        "aliases": ["a1c", "hba1c", "glycated hemoglobin"],
    },
    {
        "name": "Total Cholesterol",
        "slug": "cholesterol-total",
        "category": "Lipids",
        "canonical_unit": "mg/dL",
        "conversions": {"mg/dL": {"factor": 1}, "mmol/L": {"factor": 38.67}},
        "ref_low": None,
        "ref_high": 200,
        "aliases": ["cholesterol", "total cholesterol"],
    },
    {
        "name": "LDL Cholesterol",
        "slug": "ldl",
        "category": "Lipids",
        "canonical_unit": "mg/dL",
        "conversions": {"mg/dL": {"factor": 1}, "mmol/L": {"factor": 38.67}},
        "ref_low": None,
        "ref_high": 100,
        "aliases": ["ldl", "ldl-c", "ldl cholesterol"],
    },
    {
        "name": "HDL Cholesterol",
        "slug": "hdl",
        "category": "Lipids",
        "canonical_unit": "mg/dL",
        "conversions": {"mg/dL": {"factor": 1}, "mmol/L": {"factor": 38.67}},
        "ref_low": 40,
        "ref_high": None,
        "aliases": ["hdl", "hdl-c", "hdl cholesterol"],
    },
    {
        "name": "Triglycerides",
        "slug": "triglycerides",
        "category": "Lipids",
        "canonical_unit": "mg/dL",
        "conversions": {"mg/dL": {"factor": 1}, "mmol/L": {"factor": 88.57}},
        "ref_low": None,
        "ref_high": 150,
        "aliases": ["triglycerides", "tg"],
    },
    {
        "name": "Vitamin D (25-OH)",
        "slug": "vitamin-d",
        "category": "Vitamins",
        "canonical_unit": "ng/mL",
        "conversions": {"ng/mL": {"factor": 1}, "nmol/L": {"factor": 0.4}},
        "ref_low": 30,
        "ref_high": 100,
        "aliases": ["vitamin d", "25-oh vitamin d", "25-hydroxyvitamin d", "vit d"],
    },
    {
        "name": "Vitamin B12",
        "slug": "vitamin-b12",
        "category": "Vitamins",
        "canonical_unit": "pg/mL",
        "conversions": {"pg/mL": {"factor": 1}, "pmol/L": {"factor": 1.355}},
        "ref_low": 200,
        "ref_high": 900,
        "aliases": ["b12", "vitamin b12", "cobalamin"],
    },
    {
        "name": "TSH",
        "slug": "tsh",
        "category": "Thyroid",
        "canonical_unit": "mIU/L",
        "conversions": {"mIU/L": {"factor": 1}, "uIU/mL": {"factor": 1}, "µIU/mL": {"factor": 1}},
        "ref_low": 0.4,
        "ref_high": 4.0,
        "aliases": ["tsh", "thyroid stimulating hormone"],
    },
    {
        "name": "Free T4",
        "slug": "free-t4",
        "category": "Thyroid",
        "canonical_unit": "ng/dL",
        "conversions": {"ng/dL": {"factor": 1}, "pmol/L": {"factor": 0.0777}},
        "ref_low": 0.8,
        "ref_high": 1.8,
        "aliases": ["free t4", "ft4", "free thyroxine"],
    },
    {
        "name": "Creatinine",
        "slug": "creatinine",
        "category": "Renal",
        "canonical_unit": "mg/dL",
        "conversions": {"mg/dL": {"factor": 1}, "umol/L": {"factor": 0.0113}, "µmol/L": {"factor": 0.0113}},
        "ref_low": 0.6,
        "ref_high": 1.3,
        "aliases": ["creatinine", "serum creatinine"],
    },
    {
        "name": "Hemoglobin",
        "slug": "hemoglobin",
        "category": "Hematology",
        "canonical_unit": "g/dL",
        "conversions": {"g/dL": {"factor": 1}, "g/L": {"factor": 0.1}},
        "ref_low": 13.5,
        "ref_high": 17.5,
        "aliases": ["hemoglobin", "hgb", "hb"],
    },
    {
        "name": "Ferritin",
        "slug": "ferritin",
        "category": "Hematology",
        "canonical_unit": "ng/mL",
        "conversions": {"ng/mL": {"factor": 1}, "ug/L": {"factor": 1}, "µg/L": {"factor": 1}},
        "ref_low": 30,
        "ref_high": 400,
        "aliases": ["ferritin"],
    },
    {
        "name": "ALT (SGPT)",
        "slug": "alt",
        "category": "Liver",
        "canonical_unit": "U/L",
        "conversions": {"U/L": {"factor": 1}, "IU/L": {"factor": 1}},
        "ref_low": None,
        "ref_high": 40,
        "aliases": ["alt", "sgpt", "alanine aminotransferase"],
    },
    {
        "name": "AST (SGOT)",
        "slug": "ast",
        "category": "Liver",
        "canonical_unit": "U/L",
        "conversions": {"U/L": {"factor": 1}, "IU/L": {"factor": 1}},
        "ref_low": None,
        "ref_high": 40,
        "aliases": ["ast", "sgot", "aspartate aminotransferase"],
    },
]
